//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Immigration.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class District
    {
        public int districtId { get; set; }
        [Display(Name ="District Name")]
        public string districtName { get; set; }
        [Display(Name ="Capital Name")]
        public Nullable<int> capitalId { get; set; }
    }
}
