//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Immigration.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tblHotel
    {
        public int hotelId { get; set; }
        [Display(Name = "Hotel Name")]
        public string hotelName { get; set; }
        [Display(Name = "Region")]
        public Nullable<int> hotelRegion { get; set; }
        [Display(Name = "Address")]
        public string hotelAddress { get; set; }
        [Display(Name = "Added By")]
        public string addedBy { get; set; }
        [Display(Name = "Added Date")]
        public string addedDate { get; set; }
        [Display(Name = "Capital")]
        public Nullable<int> capitalCity { get; set; }
        [Display(Name = "District")]
        public Nullable<int> districts { get; set; }
        [Display(Name = "Contact Person")]
        public string contactPersonName { get; set; }
        [Display(Name = "Contact Number")]
        public string contactNumber { get; set; }
    }
}
